-- 미니 실습
-- DEPARTMENT테이블의 LOCATION_ID에 외래키 제약조건 추가
-- 참조 테이블은 LOCATION, 참조 컬럼은 LOCATION의 기본키


--1) DEPARTMENT 테이블을 복사하여 COPY_DEPARTMENT 테이블을 생성.
CREATE TABLE COPY_DEPARTMENT
AS
SELECT * FROM DEPARTMENT;

-- 확인
SELECT * FROM COPY_DEPARTMENT;


-- 2) 외래키 제약조건을 추가한다.
-- COPY_DEPARTMENT 테이블의 LOCATION_ID에 외래키 테이블LOCATION의 LOCAL_CODE컬럼을 참조함을 나타냄.
-- COPY_DEPARTMENT 테이블은 LOCATION테이블의 LOCAL_CODE를 사용한다.
-- LOCATION의 기본키(LOCAL_CODE)를 참조한다.
-- 부모 테이블: LOCATION
-- 자식 테이블: COPY_DEPARTMENT
ALTER TABLE COPY_DEPARTMENT ADD FOREIGN KEY(LOCATION_ID) REFERENCES LOCATION(LOCAL_CODE);
